### ISSUE TITLE
Any possible to support MacOS?

### ISSUE THREAD

**Issue by williamjin1992** [jstriaukas/midasml_mat#1]
The mex-file only support Windows and Linux, any possible to upload a .maci64 file for MacOS?
Thanks.

**Comment by jstriaukas** [comment]
Hi,

You should be able to compile the .F file provided in functions/source_code/linux as linux compiler is the same. Currently, I do not have MATLAB on mac system. As soon as I get it, I will provide the .maci64 file. Thanks!
